<?php

return [
    'withdraw_charge' => 7,
    'minumum_withdraw' => 100,
    'maximum_withdraw' => 50000,
    'minumum_deposit' => 100,
    'maximum_deposit' => 500000,
    'matching_point' => null,
    'matching_flash_point' => null,
    'minimum_matching_point_l' => null,
    'minimum_matching_point_r' => null,
    'premium_point' => null,
    'minimum_attach' => 25,
    'return_charge' => 40,

    'income_list' => [
        1 => [
            'title' => 'Refer Income',
            'name' => 'refer_income',
            'percentage' => [
                1 => 400,
                2 => 450,
                3 => 550,
            ],
            'delivery' => 'instant',
            'income_type' => 1,
            'sort' => 1,
            'middleware' => 'superadmin|admin|user',
        ],
        2 => [
            'title' => 'ROI Bonus',
            'name' => 'roi',
            'percentage' => 10,
            'delivery' => 'instant',
            'income_type' => 2,
            'sort' => 2,
            'middleware' => 'superadmin|admin|user',
        ],
        3 => [
            'title' => 'Incentive Bonus',
            'name' => 'incentive',
            'percentage' => 10,
            'delivery' => 'instant',
            'income_type' => 3,
            'sort' => 3,
            'middleware' => 'superadmin|admin|user',
        ],
        4 => [
            'title' => 'Level Bonus',
            'name' => 'generation',
            'percentage' => 60,
            'delivery' => 'instant',
            'income_type' => 4,
            'sort' => 4,
            'middleware' => 'superadmin|admin|user',
        ],
    ],
    'generation_income_list' => [
        1 => [
            'title' => '1st Level',
            'name' => 'generation',
            'percentage' => 25,
            'condition' => 0,
            'delivery' => 'instant',
            'income_type' => 4,
        ],
        2 => [
            'title' => '2nd Level',
            'name' => 'generation',
            'percentage' => 20,
            'condition' => 3,
            'delivery' => 'instant',
            'income_type' => 4,
        ],
        3 => [
            'title' => '3rd Level',
            'name' => 'generation',
            'percentage' => 15,
            'condition' => 3,
            'delivery' => 'instant',
            'income_type' => 4,
        ],
        4 => [
            'title' => '4th Level',
            'name' => 'generation',
            'percentage' => 10,
            'condition' => 3,
            'delivery' => 'instant',
            'income_type' => 4,
        ],
        5 => [
            'title' => '5th Level',
            'name' => 'generation',
            'percentage' => 8,
            'condition' => 6,
            'delivery' => 'instant',
            'income_type' => 4,
        ],
        6 => [
            'title' => '6th Level',
            'name' => 'generation',
            'percentage' => 6,
            'condition' => 6,
            'delivery' => 'instant',
            'income_type' => 4,
        ],
        7 => [
            'title' => '7th Level',
            'name' => 'generation',
            'percentage' => 4,
            'condition' => 6,
            'delivery' => 'instant',
            'income_type' => 4,
        ],
        8 => [
            'title' => '8th Level',
            'name' => 'generation',
            'percentage' => 4,
            'condition' => 9,
            'delivery' => 'instant',
            'income_type' => 4,
        ],
        9 => [
            'title' => '9th Level',
            'name' => 'generation',
            'percentage' => 4,
            'condition' => 9,
            'delivery' => 'instant',
            'income_type' => 4,
        ],
        10 => [
            'title' => '10th Level',
            'name' => 'generation',
            'percentage' => 4,
            'condition' => 9,
            'delivery' => 'instant',
            'income_type' => 4,
        ],
    ],
    'incentives' => [
        1 => [
            'title' => 'FA',
            'name' => 'FA',
            'percentage' => 10,
            'capping' => null,
            'condition_type' => null,
            'condition_count' => null,
            'condition_amount' => 5000,
            'amount' => 0,
            'sponsor_condition' => 3,
            'self_attached' => 500,
            'capping_percentage' => null,
        ],
        2 => [
            'title' => 'UM',
            'name' => 'UM',
            'percentage' => 12,
            'capping' => 7500,
            'condition_type' => 1,
            'condition_count' => 1,
            'condition_amount' => 15000,
            'amount' => 0,
            'sponsor_condition' => 5,
            'self_attached' => 1000,
            'capping_percentage' => null,
        ],
        3 => [
            'title' => 'BM',
            'name' => 'BM',
            'percentage' => 14,
            'capping' => 25000,
            'condition_type' => 2,
            'condition_count' => 1,
            'condition_amount' => 50000,
            'amount' => 0,
            'sponsor_condition' => 10,
            'self_attached' => 1500,
            'capping_percentage' => null,
        ],
        4 => [
            'title' => 'AGM',
            'name' => 'AGM',
            'percentage' => 16,
            'capping' => 100000,
            'condition_type' => 3,
            'condition_count' => 1,
            'condition_amount' => 200000,
            'amount' => 0,
            'sponsor_condition' => 20,
            'self_attached' => 2000,
            'capping_percentage' => null,
        ],
        5 => [
            'title' => 'DGM',
            'name' => 'DGM',
            'percentage' => 18,
            'capping' => 300000,
            'condition_type' => 4,
            'condition_count' => 1,
            'condition_amount' => 600000,
            'amount' => 0,
            'sponsor_condition' => 25,
            'self_attached' => 3000,
            'capping_percentage' => null,
        ],
        6 => [
            'title' => 'GM',
            'name' => 'GM',
            'percentage' => 20,
            'capping' => 1000000,
            'condition_type' => 5,
            'condition_count' => 1,
            'condition_amount' => 2000000,
            'amount' => 0,
            'sponsor_condition' => 30,
            'self_attached' => 5000,
            'capping_percentage' => null,
        ],
    ],
];
