<?php

return [
    'withdraw_charge' => 7,
    'minumum_withdraw' => 100,
    'maximum_withdraw' => 50000,
    'minumum_deposit' => 100,
    'maximum_deposit' => 500000,
    'matching_point' => null,
    'matching_flash_point' => null,
    'minimum_matching_point_l' => null,
    'minimum_matching_point_r' => null,
    'premium_point' => null,
    'minimum_attach' => 25,
    'return_charge' => 40,

    'income_list' => [
        1 => [
            'title' => 'Refer Income',
            'name' => 'sponsor',
            'percentage' => 1000,
            'delivery' => 'instant',
            'income_type' => 1,
            'sort' => 1,
            'middleware' => 'superadmin|admin|user',
        ],
        2 => [
            'title' => 'Equal Income',
            'name' => 'matching',
            'percentage' => 400,
            'delivery' => 'daily',
            'income_type' => 2,
            'sort' => 2,
            'middleware' => 'superadmin|admin|user',
        ],
        3 => [
            'title' => 'Equal Generation Bonus',
            'name' => 'matching_generation',
            'percentage' => 10,
            'delivery' => 'daily',
            'income_type' => 3,
            'sort' => 3,
            'middleware' => 'superadmin|admin|user',
        ],
        4 => [
            'title' => 'Sponsor Royalty Income',
            'name' => 'sponsor_generation',
            'percentage' => 60,
            'delivery' => 'fifteen_days',
            'income_type' => 4,
            'sort' => 4,
            'middleware' => 'superadmin|admin|user',
        ],
        5 => [
            'title' => 'Club Income',
            'name' => 'club',
            'percentage' => 0,
            'fixed' => 200,
            'delivery' => 'monthly',
            'income_type' => 5,
            'sort' => 4,
            'middleware' => 'superadmin|admin|user',
        ],
        6 => [
            'title' => 'Dealer Income',
            'name' => 'generation',
            'percentage' => 60,
            'fixed' => [
                1 => 300,
                2 => 200,
            ],
            'delivery' => 'instant',
            'income_type' => 6,
            'sort' => 4,
            'middleware' => 'superadmin|admin|user',
        ],
    ],
    'generation_income_list' => [
        1 => [
            'title' => '1st Level',
            'name' => 'generation',
            'percentage' => 25,
            'condition' => 0,
            'delivery' => 'instant',
            'income_type' => 4,
        ],
        2 => [
            'title' => '2nd Level',
            'name' => 'generation',
            'percentage' => 20,
            'condition' => 3,
            'delivery' => 'instant',
            'income_type' => 4,
        ],
        3 => [
            'title' => '3rd Level',
            'name' => 'generation',
            'percentage' => 15,
            'condition' => 3,
            'delivery' => 'instant',
            'income_type' => 4,
        ],
        4 => [
            'title' => '4th Level',
            'name' => 'generation',
            'percentage' => 10,
            'condition' => 3,
            'delivery' => 'instant',
            'income_type' => 4,
        ],
        5 => [
            'title' => '5th Level',
            'name' => 'generation',
            'percentage' => 8,
            'condition' => 6,
            'delivery' => 'instant',
            'income_type' => 4,
        ],
        6 => [
            'title' => '6th Level',
            'name' => 'generation',
            'percentage' => 6,
            'condition' => 6,
            'delivery' => 'instant',
            'income_type' => 4,
        ],
        7 => [
            'title' => '7th Level',
            'name' => 'generation',
            'percentage' => 4,
            'condition' => 6,
            'delivery' => 'instant',
            'income_type' => 4,
        ],
        8 => [
            'title' => '8th Level',
            'name' => 'generation',
            'percentage' => 4,
            'condition' => 9,
            'delivery' => 'instant',
            'income_type' => 4,
        ],
        9 => [
            'title' => '9th Level',
            'name' => 'generation',
            'percentage' => 4,
            'condition' => 9,
            'delivery' => 'instant',
            'income_type' => 4,
        ],
        10 => [
            'title' => '10th Level',
            'name' => 'generation',
            'percentage' => 4,
            'condition' => 9,
            'delivery' => 'instant',
            'income_type' => 4,
        ],
    ],
    'incentives' => [
        1 => [
            'title' => 'FA',
            'name' => 'FA',
            'percentage' => 10,
            'capping' => null,
            'condition_type' => null,
            'condition_count' => null,
            'condition_amount' => 5000,
            'amount' => 0,
            'sponsor_condition' => 3,
            'self_attached' => 500,
            'capping_percentage' => null,
        ],
        2 => [
            'title' => 'Team In-charge',
            'name' => 'TI',
            'percentage' => null,
            'capping' => null,
            'condition_type' => 'point',
            'condition_l' => 1000,
            'condition_r' => 1000,
            'condition_amount' => null,
            'amount' => 0,
            'sponsor_condition' => null,
            'self_attached' => null,
            'capping_percentage' => null,
        ],
        3 => [
            'title' => 'Impact Leader',
            'name' => 'IL',
            'percentage' => null,
            'capping' => null,
            'condition_type' => 'point',
            'condition_l' => 3000,
            'condition_r' => 3000,
            'condition_amount' => null,
            'amount' => 0,
            'sponsor_condition' => null,
            'self_attached' => null,
            'capping_percentage' => null,
        ],
        4 => [
            'title' => 'Executive Officer',
            'name' => 'EO',
            'percentage' => null,
            'capping' => null,
            'condition_type' => 'point',
            'condition_l' => 10000,
            'condition_r' => 10000,
            'condition_amount' => null,
            'amount' => 0,
            'sponsor_condition' => null,
            'self_attached' => null,
            'capping_percentage' => null,
        ],
        5 => [
            'title' => 'Assistant Manager',
            'name' => 'AM',
            'percentage' => null,
            'capping' => null,
            'condition_type' => 'point',
            'condition_l' => 25000,
            'condition_r' => 25000,
            'condition_amount' => null,
            'amount' => 0,
            'sponsor_condition' => null,
            'self_attached' => null,
            'capping_percentage' => null,
        ],
        6 => [
            'title' => 'Marketing Manager',
            'name' => 'MM',
            'percentage' => null,
            'capping' => null,
            'condition_type' => 'point',
            'condition_l' => 50000,
            'condition_r' => 50000,
            'condition_amount' => null,
            'amount' => 0,
            'sponsor_condition' => null,
            'self_attached' => null,
            'capping_percentage' => null,
        ],
        7 => [
            'title' => 'Senior Manager',
            'name' => 'SM',
            'percentage' => null,
            'capping' => null,
            'condition_type' => 'point',
            'condition_l' => 100000,
            'condition_r' => 100000,
            'condition_amount' => null,
            'amount' => 0,
            'sponsor_condition' => null,
            'self_attached' => null,
            'capping_percentage' => null,
        ],
        8 => [
            'title' => 'Assistant General Manager',
            'name' => 'AGM',
            'percentage' => null,
            'capping' => null,
            'condition_type' => 'point',
            'condition_l' => 200000,
            'condition_r' => 200000,
            'condition_amount' => null,
            'amount' => 0,
            'sponsor_condition' => null,
            'self_attached' => null,
            'capping_percentage' => null,
        ],
        9 => [
            'title' => 'Deputy General Manager',
            'name' => 'DGM',
            'percentage' => null,
            'capping' => null,
            'condition_type' => 8,
            'condition_l' => 5,
            'condition_r' => 4,
            'condition_amount' => null,
            'amount' => 0,
            'sponsor_condition' => null,
            'self_attached' => null,
            'capping_percentage' => null,
        ],
        10 => [
            'title' => 'General Manager',
            'name' => 'GM',
            'percentage' => null,
            'capping' => null,
            'condition_type' => 9,
            'condition_l' => 3,
            'condition_r' => 2,
            'condition_amount' => null,
            'amount' => 0,
            'sponsor_condition' => null,
            'self_attached' => null,
            'capping_percentage' => null,
        ],
        11 => [
            'title' => 'Executive Director',
            'name' => 'ED',
            'percentage' => null,
            'capping' => null,
            'condition_type' => 10,
            'condition_l' => 2,
            'condition_r' => 1,
            'condition_amount' => null,
            'amount' => 0,
            'sponsor_condition' => null,
            'self_attached' => null,
            'capping_percentage' => null,
        ],
    ],
];